### ISSUE TITLE
where is the back end?

### ISSUE THREAD

**Issue by YanLIU0822** [shekhar-shubhendu/supply-chain#5]
Hey 
thanks for your sharing. I also can start your project, but I cant find the back-end part, there is only the front-end, and i cannot see where is store the data.

**Comment by shekhar-shubhendu** [comment]
This is just a demo Angular SPA which uses IPFS and ethereum blockchain to store and fetch data.
There was no need of backend to demonstrate the base functionality so I haven't created it.
